spring.application.name=proxy
server.port=8081
spring.threads.virtual.enabled=true
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:3b

spring.datasource.url=jdbc:postgresql://localhost:5432/rootdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=validate
